#version：20260401
#-----------------------------------------
mixed-port: 7890
mode: rule
allow-lan: true
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
log-level: warning
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: WebUI
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: true
  stack: mixed
  device: Meta
  udp-timeout: 300
  auto-route: true
  auto-redirect: false
  auto-detect-interface: true
  strict-route: false
  dns-hijack:
    - any:53
    - tcp://any:53
  exclude-uid:
  exclude-package:
    - com.android.settings
    - com.qti.qcc

  exclude-interface:
  exclude-uid-range:

dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-filter:
     # - RULE-SET:原神域名
     - RULE-SET:私有地址
     - RULE-SET:Fake-IP-Filter

#  DNS
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 1.1.1.1
    - 8.8.8.8

#-----------------------------------------------------------------------------

#订阅设置
pp: &pp
  type: http
  interval: 21600
  health-check:
    enable: true
    url: https://www.gstatic.com/generate_204
    interval: 3600
    timeout: 3000
    lazy: true
    expected-status: 204

proxy-providers:

  🍍:
    type: inline
    payload:

#------------------------------------------------------------------------------

proxy-groups:

  - name: 选择节点
    type: select
    include-all: true

#-------------------------------------------------------------------

rule-providers:

  原神域名:
    type: http
    behavior: domain
    format: yaml
    path : ./rule_providers/原神域名.yaml
    url : https://cdn.jsdelivr.net/gh/Accademia/Additional_Rule_For_Clash@latest/China/China_Domain.yaml
    interval: 86400

  原神IP:
    type: http
    behavior: ipcidr
    format: mrs
    path: ./rule_providers/原神IP.mrs
    url: "https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo-lite/geoip/cn.mrs"
    interval: 86400

  私有地址:
    type: http
    behavior: classical
    format: text
    path: ./rule_providers/私有地址.txt
    url: https://raw.githubusercontent.com/QuixoticHeart/rule-set/refs/heads/ruleset/meta/private.list
    interval: 86400

  Fake-IP-Filter:
    type: http
    behavior: domain
    format: mrs
    path: ./rule_providers/Fake-IP-Filter.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"
    interval: 86400


 广告规则:
    type: http
    behavior: classical
    format: yaml
    path: ./rule_providers/AWAvenue-Ads-Rule-Clash.yaml
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash-Classical.yaml"
    interval: 86400

#-------------------------------------------------------------------

rules:

 - RULE-SET,广告规则,REJECT-DROP
 - RULE-SET,私有地址,DIRECT
 - RULE-SET,原神域名,DIRECT
 - RULE-SET,原神IP,DIRECT

  - MATCH,选择节点
